sonar.host.url=http://localhost:9000
sonar.projectKey=org.example:TestSonarQube
sonar.projectName=TestSonarQube
sonar.projectVersion=1.0
sonar.token=sqp_abced7854ba5a6fb4adf085af633e65f43e3e52f

# Path to source code
sonar.sources=src

# Optional: Path to tests
# sonar.tests=test

# Encoding of the source files
sonar.sourceEncoding=UTF-8
